# Generated by Django 4.0.6 on 2022-07-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courselecture_course_chapter'),
        ('account', '0007_alter_student_options_alter_teacher_options'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='account.student', verbose_name='Студент'),
        ),
    ]
