# Generated by Django 4.0.6 on 2022-07-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courselecture_course_chapter'),
        ('account', '0007_alter_student_options_alter_teacher_options'),
        ('registration', '0002_alter_courseregistration_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'verbose_name': 'реєстрація', 'verbose_name_plural': 'реєстрації'},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course', verbose_name='курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='account.student', verbose_name='студент'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='one_reg_per_student'),
        ),
    ]
