# Generated by Django 4.0.5 on 2022-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'cповіщення',
            },
        ),
    ]
