# Generated by Django 4.0.5 on 2022-06-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'cповіщення', 'verbose_name_plural': 'сповіщення'},
        ),
    ]
