# Generated by Django 4.0.5 on 2022-07-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_options_alter_teacher_options'),
        ('account', '0004_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
    ]
