# Generated by Django 4.0.5 on 2022-07-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20220708_2248'),
        ('account', '0005_merge_20220718_1901'),
    ]

    operations = [
    ]
