# Generated by Django 4.0.6 on 2022-07-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_student_user_alter_teacher_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенти'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'викладач', 'verbose_name_plural': 'викладачі'},
        ),
    ]
