# Generated by Django 4.0.5 on 2022-07-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20220722_1514'),
        ('account', '0007_alter_student_options_alter_teacher_options'),
    ]

    operations = [
    ]
