# Generated by Django 4.0.5 on 2022-06-30 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва Розділу')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Тривалість')),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='CourseLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва Лекції')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Тривалість')),
                ('course_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_lectures', to='courses.coursechapter', verbose_name='Лекція')),
            ],
            options={
                'verbose_name': 'Лекція',
                'verbose_name_plural': 'Лекції',
            },
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_chapters', to='courses.course', verbose_name='Курс'),
        ),
    ]
