# Generated by Django 4.0.5 on 2022-07-01 10:04

import courses.inc.rating
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_student_options_alter_teacher_options_and_more'),
        ('courses', '0002_course_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курси'},
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to='materials', verbose_name='зображення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=courses.inc.rating.RatingField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, verbose_name='назва'),
        ),
    ]
