# Generated by Django 4.0.5 on 2022-07-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_course_author_and_more'),
        ('courses', '0003_alter_coursechapter_options_and_more'),
    ]

    operations = [
    ]
