# Generated by Django 4.0.6 on 2022-07-09 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20220708_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name': 'розділ курсу', 'verbose_name_plural': 'розділи курсів'},
        ),
        migrations.AlterModelOptions(
            name='courselecture',
            options={'verbose_name': 'лекція курсу', 'verbose_name_plural': 'лекції курсів'},
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='рекомендований'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_title',
            field=models.CharField(max_length=100, verbose_name='назва розділу'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='courses.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), help_text='(дні год:хв:сек)', verbose_name='тривалість'),
        ),
        migrations.AlterField(
            model_name='courselecture',
            name='course_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lectures', to='courses.coursechapter', verbose_name='розділ курсу'),
        ),
        migrations.AlterField(
            model_name='courselecture',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1500), help_text='(дні год:хв:сек)', null=True, verbose_name='тривалість'),
        ),
        migrations.AlterField(
            model_name='courselecture',
            name='lecture_title',
            field=models.CharField(max_length=100, verbose_name='назва лекції'),
        ),
    ]
