# Generated by Django 4.0.6 on 2022-07-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursechapter_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursechapter',
            old_name='chapter_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='courselecture',
            old_name='lecture_title',
            new_name='title',
        ),
    ]
