# Generated by Django 4.0.6 on 2022-07-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_chapter_title_coursechapter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselecture',
            name='course_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_lectures', to='courses.coursechapter', verbose_name='розділ курсу'),
        ),
    ]
