# Generated by Django 4.0.5 on 2022-07-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20220718_1901'),
        ('courses', '0007_alter_courselecture_course_chapter'),
    ]

    operations = [
    ]
