# Generated by Django 4.0.5 on 2022-07-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='courses.coursecategory', verbose_name='категорія'),
        ),
    ]
