# Generated by Django 4.0.5 on 2022-07-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20220722_1515'),
        ('courses', '0009_remove_coursecategory_category_course_category'),
    ]

    operations = [
    ]
