# Generated by Django 4.0.5 on 2022-07-01 10:04

import courses.inc.rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=courses.inc.rating.RatingField(decimal_places=0, max_digits=1, verbose_name='рейтинг'),
        ),
    ]
