# Generated by Django 4.0.6 on 2022-07-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_student_options_alter_teacher_options'),
        ('review', '0002_alter_review_description_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.student', verbose_name='студент'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='one_review_per_course'),
        ),
    ]
