# Generated by Django 4.0.6 on 2022-07-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_review_student_review_one_review_per_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='one_review_per_course'),
        ),
    ]
