# Generated by Django 4.0.5 on 2022-06-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Відео'), ('read', 'Читання'), ('code', 'Код')], max_length=100, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('format', models.CharField(blank=True, max_length=20, null=True, verbose_name='Формат')),
                ('create_date', models.DateTimeField(verbose_name='Дата створення')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Перейти до курсу')),
                ('duration', models.DurationField(verbose_name='Тривалість')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
            },
        ),
    ]
