# Generated by Django 4.0.5 on 2022-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='create_date',
            field=models.DateTimeField(editable=False, verbose_name='Дата створення'),
        ),
    ]
